development:
  solr_core: api_cody
  tei_xsl: projects/cody_archive/scripts/solr_transform_tei.xsl

  xsl_params:
    fig_location:
    file_location: http://rosie.unl.edu/data/projects/
    figures: true
    fw: true        # form works (page nums, etc)
    pb: true        # page breaks
    project: The\ William\ F.\ Cody\ Archive
    slug: cody_archive

production:
  solr_core:
  xsl_params:
    fig_location:
    file_location:
    figures: true
    fw: true        # form works (page nums, etc)
    pb: true        # page breaks
    project:
    slug:
