default:
  project_desc: The William F. Cody Archive
  solr_core: api_cody
  collection: cody_archive
  vra_solr_xsl: scripts/overrides/vra_to_solr.xsl
  tei_solr_xsl: scripts/overrides/tei_to_solr.xsl
  tei_html_xsl: scripts/overrides/tei_to_html.xsl
  api_version: "2.0"
  threads: 20

development:
  site_url: https://servername.unl.edu/cocoon/codyarchive.org
  es_path: https://servername.unl.edu/elastic
  es_index: cdrhapidev-v1
  media_base: https://servername.unl.edu
  data_base: https://servername.unl.edu/media
  solr_path: https://servername.unl.edu/solr
  # remove once Cody is powered by orchid site
  variables_solr:
    site_url: https://servername.unl.edu/cocoon/codyarchive.org
    slug: cody_archive

production:
  site_url: https://codyarchive.org
  es_path: https://cdrhapi.unl.edu/elastic
  es_index: cdrhapi-v1
  solr_path: https://servername.unl.edu/solr
  media_base: https://servername.unl.edu
  data_base: https://servername.unl.edu/media
  # remove once Cody is powered by orchid site
  variables_solr:
    site_url: https://codyarchive.org
    slug: cody_archive
